const $=s=>document.querySelector(s),esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n/100);
let orders=[];
const next={'Recebido':'Confirmado','Confirmado':'Em preparo','Em preparo':'Pronto','Pronto':'Retirado'};
function render(){const term=$('#search').value.toLowerCase(),status=$('#status-filter').value,date=$('#date-filter').value;
 const visible=orders.filter(o=>(!status||o.status===status)&&(!date||o.data===date)&&(!term||(o.id+' '+o.nome+' '+o.telefone).toLowerCase().includes(term))).sort((a,b)=>(a.data+a.hora).localeCompare(b.data+b.hora));
 $('#order-count').textContent=visible.length+' encomenda(s)';
 $('#orders-list').innerHTML=visible.length?visible.map(o=>`<article class="admin-order"><header><div><strong>${esc(o.id)}</strong><h2>${esc(o.nome)}</h2><a href="tel:${esc(o.telefone)}">${esc(o.telefone)}</a></div><div><span class="status-pill">${esc(o.status)}</span><p>${esc(o.data.split('-').reverse().join('/'))} · ${esc(o.hora)}</p></div></header><ul>${o.items.map(i=>`<li>${i.quantity} × ${esc(i.name)} ${i.option?'· <strong>'+esc(i.option)+'</strong>':''} — ${money(i.quantity*i.cents)}</li>`).join('')}</ul>${o.observacoes?`<p><strong>Observações:</strong> ${esc(o.observacoes)}</p>`:''}<footer><strong>Total ${money(o.total)}</strong><div>${next[o.status]?`<button class="button button-dark" data-id="${o.id}" data-status="${next[o.status]}">${next[o.status]}</button><button class="cancel-button" data-id="${o.id}" data-status="Cancelado">Cancelar</button>`:''}</div></footer></article>`).join(''):'<p>Nenhuma encomenda com esses filtros.</p>';
}
async function refresh(){try{orders=await DonaAPI.orders();render();const products=await DonaAPI.products();$('#stock-list').innerHTML=products.map(p=>`<form class="stock-row" data-stock="${p.id}"><div><strong>${esc(p.name)}</strong><small>${money(p.cents)} · antecedência ${p.leadHours}h</small></div><label>Unidades disponíveis<input aria-label="Disponibilidade de ${esc(p.name)}" type="number" min="0" max="10000" step="1" required value="${p.stock}"></label><button class="button button-dark">Salvar</button></form>`).join('')}catch(e){$('#admin-message').textContent=e.message;if(e.message.includes('Entre'))showLogin()}}
function showLogin(){$('#workspace').hidden=true;$('#login-view').hidden=false;$('#logout').hidden=true}
async function showWorkspace(){$('#workspace').hidden=false;$('#login-view').hidden=true;$('#logout').hidden=DonaAPI.mode==='local';$('#mode-info').textContent=DonaAPI.mode==='local'?'Armazenamento neste navegador. Para compartilhar pedidos entre dispositivos, execute a versão com servidor.':'Pedidos centralizados da panificadora.';await refresh()}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();try{await DonaAPI.login($('#password').value);$('#password').value='';await showWorkspace()}catch(error){$('#login-error').textContent=error.message}});
$('#logout').onclick=async()=>{await DonaAPI.logout();showLogin()};$('#reload').onclick=refresh;
['search','status-filter','date-filter'].forEach(id=>$('#'+id).addEventListener('input',render));
$('#orders-tab').onclick=()=>tabs(true);$('#stock-tab').onclick=()=>tabs(false);
function tabs(orders){$('#orders-view').hidden=!orders;$('#stock-view').hidden=orders;$('#orders-tab').classList.toggle('active',orders);$('#stock-tab').classList.toggle('active',!orders);$('#orders-tab').setAttribute('aria-pressed',orders);$('#stock-tab').setAttribute('aria-pressed',!orders)}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-status]');if(!b)return;if(b.dataset.status==='Cancelado'&&!confirm('Cancelar esta encomenda e devolver os itens à disponibilidade?'))return;b.disabled=true;try{await DonaAPI.status(b.dataset.id,b.dataset.status);await refresh();$('#admin-message').textContent='Status atualizado.'}catch(error){$('#admin-message').textContent=error.message;b.disabled=false}});
document.addEventListener('submit',async e=>{const form=e.target.closest('[data-stock]');if(!form)return;e.preventDefault();try{await DonaAPI.stock(form.dataset.stock,Number(form.querySelector('input').value));$('#admin-message').textContent='Disponibilidade atualizada.'}catch(error){$('#admin-message').textContent=error.message}});
DonaAPI.init().then(async()=>{if(DonaAPI.mode==='local')await showWorkspace();else{try{await DonaAPI.orders();await showWorkspace()}catch{showLogin()}}}).catch(e=>$('#login-error').textContent=e.message);
